const TIPO_SHOCK = [
  "No registrado",
  "Séptico",
  "Cardiogénico",
  "Hipovolémico",
  "Hipovolémico/hemorrágico",
  "Neurogénico",
  "Anafiláctico",
  "Obstructivo",
  "Distributivo",
  "Mixto",
  "Séptico/cardiogénico",
  "Séptico/hipovolémico",
  "Otros",
];

const AMINAS = [
  "No registrado",
  "Norepinefrina",
  "Dopamina",
  "Dobutamina",
  "Adrenalina",
  "Vasopresina",
  "Milrinona",
  "Otros",
];

const SEDANTES = [
  "No registrado",
  "Midazolam",
  "Lorazepam",
  "Propofol",
  "Dexmedetomidina",
  "Ketamina",
  "Diazepam",
  "Clonazepam",
  "Otros",
];

const OPIOIDES = [
  "No registrado",
  "Fentanil",
  "Remifentanil",
  "Morfina",
  "Tramadol",
  "Meperidina",
  "Dexmedetomidina",
  "Ketamina",
  "Otros",
];

const RELAJANTES = [
  "No registrado",
  "Cisatracurio",
  "Vecuronio",
  "Rocuronio",
  "Otros",
];

const PANELES = [
  "No registrado",
  "Respiratorio",
  "Neumonía",
  "Líquido cefalorraquídeo",
  "Sepsis",
  "Gastrointestinal",
];

const ANTIBIOTICOS = [
  "No registrado",
  "Ninguno",
  "Aciclovir",
  "Amikacina",
  "Ampicilina",
  "Ampicilina/sulbactam",
  "Anfotericina B",
  "Azitromicina",
  "Aztreonam",
  "Carbapenémico",
  "Caspofungina",
  "Cefazolina",
  "Cefepima",
  "Cefixima",
  "Ceftarolina",
  "Ceftazidima",
  "Ceftazidima/avibactam",
  "Ceftriaxona",
  "Ciprofloxacina",
  "Clindamicina",
  "Clotrimazol",
  "Ertapenem",
  "Fluconazol",
  "Imipenem",
  "Imipenem/cilastatina",
  "IRPE",
  "Isoniazida/rifampicina/pirazinamida/etambutol",
  "Levofloxacina",
  "Linezolid",
  "Meropenem",
  "Metronidazol",
  "Oseltamivir",
  "Oxacilina",
  "Piperacilina",
  "Piperacilina/tazobactam",
  "Polimixina",
  "Polimixina B",
  "Rifaximina",
  "Tigeciclina",
  "TMP/SMX",
  "Tobramicina",
  "Trimetoprim",
  "Trimetoprim/sulfametoxazol",
  "Vancomicina",
  "Vancomicina oral",
  "Otros de amplio espectro",
];

const MICROORGANISMOS = [
  "No registrado",
  "Negativo",
  "Ninguno",
  "Contaminado",
  "Microbiota normal",
  "Microbiota bacteriana normal",
  "Acinetobacter",
  "Acinetobacter baumannii",
  "Aspergillus niger",
  "Burkholderia cepacia",
  "Burkholderia contaminans",
  "Burkholderia multivorans",
  "Candida",
  "Candida albicans",
  "Candida dubliniensis",
  "Candida glabrata",
  "Candida krusei",
  "Candida multirresistente",
  "Candida parapsilosis",
  "Candida spp.",
  "Candida tropicalis",
  "Citrobacter koseri",
  "Clostridioides difficile",
  "Coronavirus",
  "Cupriavidus necator",
  "Enterobacter",
  "Enterobacter asburiae",
  "Enterobacter cloacae",
  "Enterobacter hormaechei",
  "Enterobacterales",
  "Enterobacteria multirresistente",
  "Enterococcus casseliflavus",
  "Enterococcus faecalis",
  "Enterococcus faecium",
  "Escherichia coli",
  "Escherichia coli BLEE+",
  "Escherichia coli CTX-M",
  "Escherichia coli NDM",
  "Escherichia coli enteroagregativa",
  "Escherichia coli enteropatógena",
  "Herpes simple 2",
  "Herpesvirus",
  "Rinovirus humano",
  "Influenza",
  "Influenza tipo B",
  "Klebsiella",
  "Klebsiella aerogenes",
  "Klebsiella oxytoca",
  "Klebsiella pneumoniae",
  "Klebsiella pneumoniae BLEE",
  "Klebsiella pneumoniae NDM",
  "Klebsiella pneumoniae/Escherichia coli",
  "Kodamaea ohmeri",
  "Metapneumovirus",
  "Moraxella catarrhalis",
  "Morganella morganii",
  "MTB trace detected",
  "Norovirus",
  "Parainfluenza B",
  "Proteus mirabilis",
  "Proteus spp.",
  "Pseudomonas aeruginosa",
  "Rotavirus",
  "Salmonella spp.",
  "Salmonella Typhi",
  "Saprochaete capitata",
  "Serratia marcescens",
  "Staphylococcus aureus",
  "Staphylococcus aureus CTX-M",
  "Staphylococcus aureus meticilino sensible",
  "Staphylococcus aureus meticilino resistente",
  "Staphylococcus epidermidis",
  "Staphylococcus haemolyticus",
  "Staphylococcus hominis",
  "Staphylococcus spp.",
  "Stenotrophomonas maltophilia",
  "Streptococcus oralis",
  "Streptococcus pneumoniae",
  "Streptococcus agalactiae",
  "TB pulmonar",
  "Trichosporon asahii",
];

const CATALOGOS_POR_CAMPO: Record<string, string[]> = {
  panel_1: PANELES,
  panel_2: PANELES,
  panel_3: PANELES,
  tipo_de_shock: TIPO_SHOCK,
  que_tipo_de_amina: AMINAS,
  que_tipo_de_amina_2: AMINAS,
  que_tipo_de_sedante_1: SEDANTES,
  que_tipo_de_sedante_2: SEDANTES,
  que_tipo_de_opiode_1: OPIOIDES,
  que_tipo_de_opiode_2: OPIOIDES,
  que_tipo_de_relajante: RELAJANTES,
  tipo_de_antibiotico_1: ANTIBIOTICOS,
  tipo_de_antibiotico_2: ANTIBIOTICOS,
  tipo_de_antibiotico_3: ANTIBIOTICOS,
  microorganismo_panel_1: MICROORGANISMOS,
  microorganismo_panel_2: MICROORGANISMOS,
  microorganismo_panel_3: MICROORGANISMOS,
  microorganismo_1: MICROORGANISMOS,
  microorganismo_2: MICROORGANISMOS,
  microorganismo_3: MICROORGANISMOS,
  microorganismo_4: MICROORGANISMOS,
};

export function catalogoCriticoPorCampo(key: string): string[] {
  return CATALOGOS_POR_CAMPO[key] ?? [];
}
