FROM eclipse-temurin:21-jre AS jre

FROM node:20-slim

ENV JAVA_HOME=/opt/java/openjdk
COPY --from=jre ${JAVA_HOME} ${JAVA_HOME}
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# Firestore emulator requiere Java
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g firebase-tools

WORKDIR /firebase

COPY firebase.json .
COPY firestore.rules .
COPY storage.rules .

# Pre-descarga los binarios de los emuladores en la imagen
RUN firebase setup:emulators:firestore --project demo-esdomed && \
    firebase setup:emulators:storage --project demo-esdomed

EXPOSE 4000 8080 9099 9199 4400 4500

CMD ["firebase", "emulators:start", "--project", "demo-esdomed"]
